[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa44f6deca6397a6d2d638e824ba2022c069540f"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "bb7dc8799ea75d851c5d24ab1235927a72076a061664e0617361292582c337a0"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.aarch64-linux-musl-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d314bc2361211027ae4a5515a8e1b97d43e8318"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "ba0401a6a6bc2174cee1fe98fa8fc41d55bffdcecf09737135996ad3b8da66a2"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.aarch64-linux-musl-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "046ba7802eb88c9c1ef22f6f7d2bc64a413201e6"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "57d03eeadc7697b0401900c366f2415e8b74d69350bf6bd26e62084a0ea089fd"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31ee300b72294e2ad86c7bd57e408c31dbbffe12"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "42a50f73db6f3bb4735be7f4b8d9321b37b4a6ae39a32892773e848312b7d392"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-w64-mingw32-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e11c8232dca9b21251b20aca1d43de99185b451"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "1aa1d8583bf811061c7b4c2dcc0cc64ddd4c8ac50f8ea0bd8227e303724b440b"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.i686-linux-musl-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4df2e88ccab03031b3e5bdec9075c7d7ca79578"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "3705ff98e21a493eaed2003efefeacf33418f038600bc6b7a8195827122f283a"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-linux-musl-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2e20d20ddd410a31310e3322a7b79bc6cd80df6"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "5cdda2bccdf1de90dfa06238111420feb50b26675931df7a1ded7b5128a6ea33"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eded297d9e4cbd1bf21f75146f982ba25058f6e3"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "ffbcbdcb5a17d16308206e0f6e62d50496ab77392c108337b1a5e7c643d7e886"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.i686-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c5a3523ef82da6ee0387fa880fbbecd9b2281ce"
os = "macos"

    [[LibSpatialIndex.download]]
    sha256 = "2ccbc9e2577b66f4779f8b630568759111d2212144e1caa5ac0a690e7d6324b5"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1320badf820c08a8db901df296757d430322f97c"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "c781d36a4bf2bda7d55c2740c00eda506c3f8da7a76491ad717a193ae6a4b6ca"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.i686-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2209f37c43c15edd3363c8b2b9366b20c5a78000"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "0ade842dabe74ca7fca8aff58e8c0881a4f4c8d8d34032c76b26d765bcab322a"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58c476dac9e3d0a78445bfc3407fc315f89097e7"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "796c72695ca81b9f1764e02132343bba6e5d2b8cd830e1f5ca2f5a8316ddd708"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73c985b31813995b661f11527c1e2b94ee9579da"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "3505bf788da891c4339bbc5ed7f6a2bdc66cacd28a42703e6e883429fb870a6d"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "298ca528a32eb4eac373dc38c3469e1ae73e1266"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "9d739a46eef33eec77d0bc6685ebe8837c5ff737d233624f69b2da0553d9d73f"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.aarch64-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18eb8bf12330bd72047a13aece9b22f075356066"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "eb312a6bf331a8fa5b5238fd1947eb7f16186a79a91947d05c4301e9b12a791d"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-linux-musl-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c39226a1f2c4978df1c757437530a5af6585efee"
os = "macos"

    [[LibSpatialIndex.download]]
    sha256 = "409156dd62d5db0d7a7fbe9563e924039467c9718d435f4d0e398a106cc382b3"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e88922d2748d2d54f72ee4dda0603ee25abe416a"
os = "freebsd"

    [[LibSpatialIndex.download]]
    sha256 = "10884fb5618ff018736e49696ba4f8667f75d77328c330bac81ee2d41a19add1"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22bdf2644fba6963063eb53e4612354401413114"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "eef7e64370e6ac8a478160dff4c09c497a517c769adbbb94d60855d7036a207e"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc0b82e17aaffbf5d31a06baf8f0806b5369b86c"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "83d1cfa06ef62a69a1f5e895ffe2918ebc6d640019937d25f8f90f881df25200"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.i686-w64-mingw32-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c7233acfc2c3da229c8b8c502921703dd524ad6"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "95af313d471bc1699eed61a934ba8ae69af05f07eafbcf61f7cf38bacecb6db4"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.i686-w64-mingw32-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "006075d938b3b59553ab5b3af03b220962c7a90d"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "b465675b0571f0f7c15408bfff8e167f9fbeba834822266de7e90109db70fbec"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b27b3981db286392c0b3ea50f27083b05273d50a"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "cfa01ee0df9749c700239b783870b6f28658fb3b471843ec0d130cb5bb433d25"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9176fbcea2e1be46e41b0a447924e75f4d109d7"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "0cfa7a796d2f70cc54820e345c68e372940904266fd9ecfcbc0aad17284c5a17"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.aarch64-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "097d386a6f61c3175b4466ebc0552dad5bf66a47"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "e66e318dae30594fdf9a02e09d8ae8a53719eeee1307a0bb582c7146f050746d"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baaabe212289ee0844b81bf06653d9036e23b8c1"
os = "freebsd"

    [[LibSpatialIndex.download]]
    sha256 = "74c5139e2d722673c9577ed7caca2bfa515c31382673043e01bb76c9b3684a36"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce2aae15e215a2960c5716b6bb87a7c74ef45fd6"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "9f81ce0bfeae661aec43c3fb3894f4b21f0fbb947351208e8610377017c46348"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.8.5+0/LibSpatialIndex.v1.8.5.i686-linux-musl-cxx03.tar.gz"
