[[LibSpatialIndex]]
arch = "aarch64"
git-tree-sha1 = "227dc98bbe34da36bda0e35bfedde5dd187f539e"
os = "macos"

    [[LibSpatialIndex.download]]
    sha256 = "f2751028e46c859e1e4a3322677602d51fa43c6a8f07f13dd4a05e56bbbbd336"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.aarch64-apple-darwin.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7d62a4a6d6b0a85d693bb1017a39f2fe91894ca"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "dd0b412e9584c5d74611bc4c1610369d878d45b9d37e4a7026865a592d2e7cde"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.aarch64-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "888eb52c2a66ca3265e9dadd873f7e08148d7d22"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "0ba86236aadfdf4067433a84d65e3e01f9159d46a70f5cbccb938841eb9d2712"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.aarch64-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22341650f901f25a2c12a81c2d2d08d7b21b5d9d"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "f31cac1b55181548c9cc137c21561627db55609583b7ff11fb8288ca53108c08"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.aarch64-linux-musl-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdaa141bba8169db2ba37f751ad5116d41ed3ecf"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "1ce55e85d6230a50b13dad61aa7bddb1cfa9dd0d13f92bf206336d9fa693e5a7"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.aarch64-linux-musl-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd428ce7c196b91de4c37bbe649e62a31521e647"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "7306a6682a2b51e6ea86235466e8b752310077f82ea8a968960e86bde68f64a7"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d728aedb4ae27527c667cf67a3af0e562fb0599"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "07484039c7133b5be5fbe7d592e66d5e5bda8c0fa85f933d729ade20057f780e"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6897da84ec9b21c52e1fc9f1599d205e427c3a87"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "669b95406a656bd77552c640bbd5fb36e814467a081e263b7b1fe9fc0d0b6586"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "273356eb35fe402cd631203e751b61dfa6d272a6"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "9515c6c984d2cd2ea2a0da9e041b580c294076d492dcd098950aff2d77e0c9ad"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "629958fd3e47ff7834c0a69b5b1818b82fff8a1d"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "50a308d4e40cadb9b371a25dd8292fb45e711aa93982d5bd949274ff1f410729"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8095981c32d365f904f90aa9e28a08ed428e823"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "38e653659b37078da36c03165ee2f72d7d20f705419a747c3b2e4a529e0a2367"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0c5930b4cbed066452b7d3fc95459253320b837"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "32cfa18fc1cd4b44567a1b87f1acc51a3b54455450c3cb7d7ab6c96b95a725e2"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "475c5dc8d3d2c429b646ac524b70cf14a673a039"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "044b09801c3689c46d61be566d0c4a50709ab4a04f5d450b0334a630e31d464d"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1115c793d9d40162d7a500c899055e9c6b36787a"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "46e92eac4f757b96572502b0fa595f1d03ff39cff31507fb82070df32dfbd379"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.i686-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e7418c0c9f39af12a910a9371d4fd3fc605683c"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "a2360f3687e555b26eb0edfb150b32aa3d87f19b7b5fc0d979ecd6a900679986"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.i686-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "910737200d446101c1ace97d2219811d11be48cf"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "227b9957032f0bd0b6a49ac44594c1811eed50d67fc0c2c773391161c0a8580e"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.i686-linux-musl-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e51592ad167b4961f2c84c0dc8dfd0067a6cb4ff"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "afc3c9417bf35940a1485f6411efa12408434912b86b52f811829f502e2ba3df"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.i686-linux-musl-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68d754eb1c39b5a1d68578e516e59226c268c901"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "6fe0adf6e4b134471825ac925634656fec23545b72057f723b189bf544b05b32"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.i686-w64-mingw32-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cd99b3efe653205dc8783dd4d4680c7d735a76e"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "8fa11f45936e2c447ef2638e03aa0af6b39b7228a7719df2b929940d68826274"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.i686-w64-mingw32-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f97f97a0a8aade53b2b0a32a12d5815bd9ba2fc"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "3d0208bdf249e7ad43d837fd131591e7c5b64f4bcfc838ad2858ee9ff7600b08"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8604bc391a3e433459c39ce02643b4cd613d6d10"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "e3be42711d0343b69edab295d583e19c4664536b9bb6c45de800cec25e9b4349"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
git-tree-sha1 = "5f882f7cfc3f94446a9be278d8aa8ef72a9746a9"
os = "macos"

    [[LibSpatialIndex.download]]
    sha256 = "2d24d37906423f2f11b0190ead99df995f98bc4ecccfcd755881ae3f866ee8bb"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-apple-darwin.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adf9923461acb2977727af929560177ab6ef5f46"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "cde04151602dc2e6e24ab2dd51f6344aa4dc25b390d2ad9f32f362c2a6cf5a3f"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-linux-gnu-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a1541a10d72f48c1e5e16881849ea8aa4f15ac1"
libc = "glibc"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "44567a5fcbe8454da507a185b17e0028ff53d5517b3a131544fc615ffc10c9fc"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-linux-gnu-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99c59a887353da24a9eca85797754e57e1321e3e"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "32bd3c745faf5e2a702b93742f89ba5bb9c7f6a1be2a24898fc9492d133ef613"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-linux-musl-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5e3c930511485c9b5db1de4ae2e5f5973556bc8"
libc = "musl"
os = "linux"

    [[LibSpatialIndex.download]]
    sha256 = "c93ce503039c60ee22254868d08864da207e0c9c4290be933cd03988afbe2d9e"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-linux-musl-cxx11.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
git-tree-sha1 = "8a1015083d9fd711b213af55a4781b0dcd0667b1"
os = "freebsd"

    [[LibSpatialIndex.download]]
    sha256 = "aa4e8b48dedecd3afdbe63c437ae1853ab1ac8f81a0e7f1188323e648dcbecb4"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-unknown-freebsd.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9e8ee9481069ab91718792cb2c01195be1fc853"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "a9c2f048c1046931bdd158ef2b11078dce8ef428f0902286ce02c0b46781162b"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[LibSpatialIndex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cc4aa76845e7db87cd181007a67912632661d63"
os = "windows"

    [[LibSpatialIndex.download]]
    sha256 = "eba952bb862c4cbb0a263b9df9514d47abfbf401f0ed3d6af1e4d3661fcf9164"
    url = "https://github.com/JuliaBinaryWrappers/LibSpatialIndex_jll.jl/releases/download/LibSpatialIndex-v1.9.3+0/LibSpatialIndex.v1.9.3.x86_64-w64-mingw32-cxx11.tar.gz"
