# Autogenerated wrapper script for LibSpatialIndex_jll for x86_64-w64-mingw32-cxx03
export libspatialindex, libspatialindex_c

JLLWrappers.@generate_wrapper_header("LibSpatialIndex")
JLLWrappers.@declare_library_product(libspatialindex, "libspatialindex.dll")
JLLWrappers.@declare_library_product(libspatialindex_c, "libspatialindex_c.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libspatialindex,
        "bin\\libspatialindex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspatialindex_c,
        "bin\\libspatialindex_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
